### ISSUE TITLE
Error: spawn zcashd ENOENT

### ISSUE THREAD

**Issue by dexter369** [radix42/zcash-block-explorer#1]
[2017-02-20T14:34:21.964Z] error: Error: spawn zcashd ENOENT
    at exports._errnoException (util.js:907:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:189:32)
    at onErrorNT (internal/child_process.js:355:16)
    at nextTickCallbackWith2Args (node.js:458:9)
    at process._tickCallback (node.js:372:17)

**Comment by radix42** [comment]
It looks like its not starting up zcashd correctly, what's the output of the command "which zcashd", and what's the contents of bitcore-node.json?

**Comment by dexter369** [comment]
which zcashd does not return any output
and for zcashd, I get error:
zcashd: command not found

bitcore-node.json has default values as per script:

{
  "network": "mainnet",
  "port": 3001,
  "services": [
    "bitcoind",
    "insight-api-zcash",
    "insight-ui-zcash",
    "web"
  ],
  "servicesConfig": {
    "bitcoind": {
      "spawn": {
        "datadir": "./data",
        "exec": "zcashd"
      }
    }
  }
}

**Comment by radix42** [comment]
It assumes you've installed zcashd into somewhere in your path via the deb
package that the part 1 script builds (/usr/local/bin by default). It
sounds like something in that script went awry

**Comment by dexter369** [comment]
Tried to run the 1st script multiple times each time on fresh vps, but "which zcashd" never worked after running the first script. I got the following error somewhere in middle but the script reached the end with message to logout:

Warning: end of file not at end of a line; newline inserted
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
Makefile:4158: recipe for target 'libbitcoin_server_a-init.o' failed
make[2]: *** [libbitcoin_server_a-init.o] Error 4
make[2]: Leaving directory '/home/sammy/zcash/src'
Makefile:7704: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/sammy/zcash/src'
Makefile:679: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by radix42** [comment]
what linux distro are you on? that error indicates that it does not
successfully compile zcash, in which case nothing else is going to work

**Comment by dexter369** [comment]
ubuntu 16.04 vps

**Comment by dexter369** [comment]
tried with debain 8, got similar error:
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
Makefile:4145: recipe for target 'libbitcoin_server_a-init.o' failed
make[2]: *** [libbitcoin_server_a-init.o] Error 4
make[2]: Leaving directory '/home/sammy/zcash/src'
Makefile:7691: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/sammy/zcash/src'
Makefile:667: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by radix42** [comment]
what happens when you try to build from source by hand, as directed here:
https://github.com/zcash/zcash/wiki/1.0-User-Guide
Alternatively you can install the pre-built binaries

**Comment by dexter369** [comment]
Thanks a lot, finally got it working using pre-built binaries.
